### ISSUE TITLE
Files Larger than about 2MB Upload but gives Internal Server Error

### ISSUE THREAD

**Issue by ghost** [maxpavlov/jQuery-File-Upload.MVC3#4]
Hi there,
Hi there, what could this be caused by?  I have the maxRequestLength set much higher.  The file gets uploaded to the server but then it comes back with "Internal Server Error"...  doesn't matter the file type... jut the size.

I am not using any of the picture preview stuff, nor the thumbnails.  Most of the infrastructure is still there for it, but the templates don't refer to it anymore.

Environment is Win2008 Server; MVC3

**Comment by mehrdadg11** [comment]
I have this problem too, i dont have ashx file, and i use action instead of ashx file.
when i use ashx doesnt execute uploadfile method.
